name: Development Release On S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
          ref: main  # Use main branch after version update

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Cache Rust dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-deps-x86_64-unknown-linux-gnu-stable-v1
          restore-keys: |
            cargo-deps-x86_64-unknown-linux-gnu-stable-

      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            target/
          key: cargo-build-x86_64-unknown-linux-gnu-stable-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            cargo-build-x86_64-unknown-linux-gnu-stable-

      - name: Build the binary
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          CARGO_BUILD_TARGET: x86_64-unknown-linux-gnu

      - name: Prepare binary for release
        run: |
          mkdir -p release-files
          # Copy the binary to the release directory
          cp target/x86_64-unknown-linux-gnu/release/tracer release-files/tracer

          # Make the binary executable
          chmod +x release-files/tracer

          # Create tar.gz file with the desired name and correct file structure
          tar -czf release-files/tracer-x86_64-unknown-linux-gnu.tar.gz -C release-files tracer

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp release-files/tracer-x86_64-unknown-linux-gnu.tar.gz s3://tracer-releases/tracer-x86_64-unknown-linux-gnu.tar.gz